### ISSUE TITLE
Long subjects need trimming on the inbox view

### ISSUE THREAD

**Issue by xray7224** [Inboxen/website#88]
Currently when a message like:

https://inboxen.org/inbox/muhda@inboxen.org/view/1d8b9

comes into inboxen it looks stupid due to the subject... we could try using css to do this I believe we could look into:

```
overflow: hidden;
```

If the user has JS possibly actually viewing the email it's self we could condense it and only when you put your mouse over it for a bit it expands the breadcrumb? I don't know...

**Comment by moggers87** [comment]
Closing this - it looks fine to me on smaller screens
